language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
      r_check_args: '--use-valgrind'
    - os: osx
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
    - valgrind

notifications:
  email:
    on_success: change
    on_failure: change
