language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

r_github_packages:
  - jimhester/covr

addons:
  apt:
    packages:
    - valgrind

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
